/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_cerus_etstelemetry_sharedmem_NativeMemoryMappedFile */

#ifndef _Included_dev_cerus_etstelemetry_sharedmem_NativeMemoryMappedFile
#define _Included_dev_cerus_etstelemetry_sharedmem_NativeMemoryMappedFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_cerus_etstelemetry_sharedmem_NativeMemoryMappedFile
 * Method:    read
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_dev_cerus_etstelemetry_sharedmem_NativeMemoryMappedFile_read
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
